version: '3.9'

services:
  app_docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_app_docker:1.1
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://docker_app:3306/docker?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: DSML1
    depends_on:
      - docker_db
    restart: always

  docker_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DSML1
      MYSQL_PASSWORD: DSML1
      MYSQL_DATABASE: docker_app
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 10
